### ISSUE TITLE
Load times for Malli namespaces

### ISSUE THREAD

**Issue by RokLenarcic** [fulcrologic/guardrails#41]
Unfortunately it takes a long time to load Malli namespace:
```
(time (require '[com.fulcrologic.guardrails.malli.core]))
"Elapsed time: 7574.215667 msecs"
```
Since this namespace require happens even if Guardrails is disabled (e.g. production), it would be nice to think about alternative ways to load the required namespaces to avoid that hit in production.

Another key insight is that about half of it is just the printer/reporter.

```
(time (require '[malli.dev.pretty :as mp]))
"Elapsed time: 3335.58975 msecs"
```

Malli's dev printer is very expensive to load, because it uses Fipp which takes a long time to load, and Fipp uses core.rrb-vector which is also heavy.

**Comment by awkay** [comment]
Open to suggestions. It's a bit messy. The easiest thing to do in order to make CLJC work perfectly is to make a stubs lib, but this could wreak havoc at the classpath level should a library author export it.  So, I don't like that approach.

Doing it in CLJ isn't that bad, since dynamic ns loading is possible, but in CLJS it's a lot messier.

I think perhaps the safest thing to do is to make local source files that are in a separate source folder that can act as noop stand-ins. When you build/run for production, you switch from dev mode (which has GR on the CP) to prod mode (which removes GR and includes the stubbed source folder). That way you don't have to worry about a convoluted mess on your classpath.  I think deps always puts source folders earlier on the classpath, which means even if GR was on the classpath it would prefer your stubs...but not sure what that would look like in an uberjar...you'd have to be very careful with your classpath either way, but by making your own little stubs you can avoid any library madness that might ensure if we were to do it.

**Comment by gnl** [comment]
I think the solution here is having a stubs version of the regular Guardrails artifact rather than a separate stubs library. So for example if the newest Guardrails version is 1.2.4, the corresponding stubs version would be 1.2-stubs, with noop namespaces for the full 1.2.x API.

This solves the potential issue of multiple artifacts in the dependency tree (regular and stubs library) providing conflicting namespaces – only one version will ever be on the classpath and the default will always be the regular one:
- when using tools.deps, newest version wins, and 1.2.x is newer than 1.2-stubs.
- when using Leiningen/Maven, nearest-to-the-root version wins, so again that would be the manually required regular version, rather than the stubs version possibly required by a dependency.

Furthermore, the stubs version can be easily forced in a `deps.edn` production alias with:

`{:aliases {:prod {:override-deps {com.fulcrologic/guardrails {:mvn/version "1.2-stubs"}}}}}`

...thus ensuring full Guardrails elision across all platforms.

EDIT:

To be even more on the safe side, the stubs version could be "0-stubs-1.2", which would be older than any actual Guardrails version ever released, and there would be no risk of unintentional override even if someone were still using an older Guardrails.

- [Maven – POM Reference](https://maven.apache.org/pom.html#version-order-specification)

**Comment by RokLenarcic** [comment]
Very clever.

But more on the point of load times: I see that `com.fulcrologic.guardrails.malli.core` loads `com.fulcrologic.guardrails.core` so it also always loads the spec stuff. It loads `expound` even though it is not used.

Another big, big load is core.async. That one takes a long time to load and it's only used if async checks are used. There's probably a way to make that queue work in a way that doesn't require core.async dependency.

**Comment by gnl** [comment]
Personally, I'd be satisfied with the stubs-version solution in production, and probably wouldn't want to invest the time to shave off a few seconds on the initial load during development (especially if the solution might result in added complexity),  but let's see what @awkay has to say about all of this.

**Comment by RokLenarcic** [comment]
Well I am trying to add guardrails to a CLI app and not spending 7 seconds to load the malli ns is a pretty big usability difference. I know that in servers that's not considered a big deal.

My analysis of the situation is that we could get rid of the core.async dep. It's large, tons of code, and slow. Using it for one simple queue seems a total overkill.

**Comment by gnl** [comment]
All good, I'd be happy to see a PR that makes it load faster. And actually I'm not sure we even need the async stuff anymore after the recent performance improvements and MCPS/throttling support.
